[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    regression: для регрессионных тестов.
    registration: Маркировка для регистрации
    smoke: Маркировка для смок тестов
    critical: Маркировка для критичных тестов
    ui: Маркировка для ui тестов
    slow: Маркировка для медленных тестов
    authorization: Маркировка для тестов, связанных с авторизацией пользователей
    courses:  для тестов, связанных с курсами.
